### PR TITLE
Fix bug when label name is equal to file name in recent file list.

### LINKED ISSUE #826: Question on Recent Files List with UseTitleInRecentFileList set to True
With the above setting, I get the following.

Untitled

It seems that it repeats the entire filename in the parentheses which makes the list really long unnecessarily. I'm not sure if this is because the files I have are lacking some metadata HC is looking for.

### PR DESCRIPTION
**Pull request by lifegpc**
Fix #826

### CODE REVIEW

File: src/mpc-hc/MainFrm.cpp [hunk 1]
```diff
@@ -12104,7 +12104,8 @@ void CMainFrame::OpenFile(OpenFileData* pOFD)
                 r.fns.AddTail(fn);
                 CPlaylistItem* m_pli = m_wndPlaylistBar.GetCur();
                 if (!m_pli->m_label.IsEmpty()) {
-                    if (!m_pli->m_bYoutubeDL || fn == m_pli->m_ydlSourceURL) r.title = m_pli->m_label;
+                    if (!m_pli->m_bYoutubeDL && PathUtils::StripPathOrUrl(fn) == m_pli->m_label);
```
Comment (clsid2) [inline src/mpc-hc/MainFrm.cpp]: You can change the first if/else to an if statement.
`if (m_pli->m_bYoutubeDL || PathUtils::StripPathOrUrl(fn) != m_pli->m_label) {`

ReverseFind also needs fixing, as that has a char parameter, and not a string pointer.

File: src/mpc-hc/MainFrm.cpp [hunk 2]
```diff
@@ -13195,12 +13196,12 @@ void CMainFrame::OpenSetupWindowTitle(bool reset /*= false*/)
                     }
                 }
 
+                if (has_title & title != GetFileName()) m_current_rfe.title = title;
```
Comment (clsid2) [inline src/mpc-hc/MainFrm.cpp]: Maybe add `CString fn = GetFileName()` so that GetFileName() does not need to be called twice.
